import { createContext, useState, useEffect } from 'react'

export const LanguageContext = createContext()

const translations = {
  en: {
    home: 'Home',
    laws: 'Laws',
    assistant: 'AI Assistant',
    about: 'About',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    dashboard: 'Dashboard',
    profile: 'Profile',
    bookmarks: 'Bookmarks',
    search: 'Search',
    searchPlaceholder: 'Search laws, articles, or ask a question...',
    searchResults: 'Search Results',
    noResults: 'No results found',
    criminalLaw: 'Criminal Law',
    familyLaw: 'Family Law',
    laborLaw: 'Labor Law',
    constitution: 'Constitution',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    footerDescription: 'Ethiopian Law Guidance System - Making justice accessible to all through technology.',
    copyright: 'Ethiopian Law Guidance System. All rights reserved.',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    contact: 'Contact Us',
    aiAssistant: 'Legal AI Assistant',
    aiAssistantDescription: 'Ask me about Ethiopian Criminal, Family & Labor Law',
    online: 'Online - 24/7',
    send: 'Send',
    aiDisclaimer: 'This AI provides general legal information only. For specific legal advice, consult a qualified lawyer.',
    suggestedQuestions: 'Suggested questions:',
    chatPlaceholder: 'Type your legal question here...',
    all: 'All',
    keyword: 'Keyword',
    naturalLanguage: 'Natural Language',
    searching: 'Searching legal database...',
    tryDifferentKeywords: 'Try different keywords or browse legal categories below',
    results: 'results',
    foundIn: 'found in',
    sortByRelevance: 'Sort by: Relevance',
    sortByDate: 'Sort by: Date',
    sortByTitle: 'Sort by: Title',
    views: 'views',
    share: 'Share',
    readMore: 'Read More',
    clearAll: 'Clear All',
    allCategories: 'All Categories',
    allLanguages: 'All Languages',
    allTime: 'All Time',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    thisYear: 'This Year',
    clearHistory: 'Clear History',
    useKeywords: 'Use Keywords',
    keywordsTip: 'Try specific terms like "divorce", "theft", or "minimum wage"',
    naturalLanguageTip: 'Ask questions like "What are the grounds for divorce?"',
    browseCategories: 'Browse Categories',
    browseTip: 'Or explore laws by category if you\'re not sure what to search',
    loadingCategory: 'Loading category...',
    categoryNotFound: 'Category not found',
    backToCategories: 'Back to Categories',
    articles: 'articles',
    showing: 'Showing',
    of: 'of',
    last30Days: 'Last 30 Days',
    mostPopular: 'Most Popular',
    saves: 'saves',
    quickSearch: 'Quick search...',
    viewAll: 'View All',
    newSearch: 'New Search',
    startChat: 'Start Chat',
    savedArticles: 'Saved Articles',
    recentActivity: 'Recent Activity',
    recommended: 'Recommended for You',
    quickAccess: 'Quick Access',
    continueLearning: 'Continue Learning',
    continue: 'Continue',
    searchedFor: 'Searched for',
    saved: 'Saved',
    askedAbout: 'Asked about',
    basedOnSearches: 'Based on your recent searches',
    popularInProfession: 'Popular in your profession',
    frequentlyViewed: 'Frequently viewed',
    loadingDashboard: 'Loading your dashboard...',
    viewAllActivity: 'View All Activity',
    allBookmarks: 'All Bookmarks',
    items: 'items',
    export: 'Export',
    mostViewed: 'Most Viewed',
    lastAdded: 'Last added',
    total: 'Total',
    categories: 'Categories',
    criminalCode: 'Criminal Code',
    viewed: 'Viewed',
    hoursAgo: 'hours ago',
    loadingBookmarks: 'Loading your bookmarks...',
    loginToViewBookmarks: 'Please log in to view your bookmarks',
    goToLogin: 'Go to Login',
    noBookmarks: 'No bookmarks yet',
    startSavingContent: 'Start saving legal content to access them quickly here',
    browseLaws: 'Browse Laws',
    selectAll: 'Select All',
    remove: 'Remove',
    personalInfo: 'Personal Information',
    fullName: 'Full Name',
    email: 'Email Address',
    phone: 'Phone Number',
    profession: 'Profession',
    selectProfession: 'Select profession',
    student: 'Student',
    lawyer: 'Lawyer',
    judge: 'Judge',
    legalResearcher: 'Legal Researcher',
    businessOwner: 'Business Owner',
    other: 'Other',
    bio: 'Bio',
    bioPlaceholder: 'Tell us a little about yourself...',
    saveChanges: 'Save Changes',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    passwordRequirements: 'Password Requirements:',
    minLength: 'At least 6 characters long',
    uppercaseRequired: 'At least one uppercase letter',
    numberRequired: 'At least one number',
    updatePassword: 'Update Password',
    preferences: 'Preferences',
    displaySettings: 'Display Settings',
    language: 'Language',
    fontSize: 'Font Size',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    darkMode: 'Dark Mode',
    notifications: 'Notifications',
    emailNotifications: 'Email Notifications',
    savePreferences: 'Save Preferences',
    accountStatus: 'Account Status',
    verified: 'Verified',
    notVerified: 'Not verified',
    disabled: 'Disabled',
    memberSince: 'Member Since',
    manageAccount: 'Manage Account',
    securityTips: 'Security Tips',
    useStrongPassword: 'Use a strong password',
    enable2FA: 'Enable 2-factor authentication',
    dontShareCredentials: 'Don\'t share your credentials',
    logoutFromSharedDevices: 'Log out from shared devices',
    connectedAccounts: 'Connected Accounts',
    connected: 'Connected',
    connect: 'Connect',
    loadingProfile: 'Loading profile...',
    loggedInFromNewDevice: 'Logged in from new device',
    chatWithAI: 'Chat with AI assistant',
    loginToViewProfile: 'Please log in to view your profile',
    searches: 'Searches',
    chatSessions: 'Chat Sessions',
    bookmarks: 'Bookmarks',
    security: 'Security',
    accessibility: 'Accessibility for all',
    accuracy: 'Accuracy and reliability',
    multilingual: 'Multilingual inclusion',
    userCentered: 'User-centered design',
    continuousImprovement: 'Continuous improvement',
    fragmentedInfo: 'Fragmented Information',
    fragmentedInfoDesc: 'Legal information scattered across multiple sources',
    languageBarriers: 'Language Barriers',
    languageBarriersDesc: 'Limited access in local languages',
    noRealTime: 'No Real-time Assistance',
    noRealTimeDesc: 'Lack of instant legal guidance',
    geographicLimitations: 'Geographic Limitations',
    geographicLimitationsDesc: 'Rural areas have limited access',
    multiPlatform: 'Multi-Platform Access',
    multiPlatformDesc: 'Web and mobile applications for anytime, anywhere access',
    multilingualSupport: 'Multilingual Support',
    multilingualSupportDesc: 'Content available in English, Amharic, and Afaan Oromoo',
    aiPowered: 'AI-Powered Assistant',
    aiPoweredDesc: 'Natural language processing for instant legal queries',
    centralizedRepo: 'Centralized Repository',
    centralizedRepoDesc: 'All Ethiopian laws in one verified database',
    getStarted: 'Get Started',
    contactUs: 'Contact Us',
    askNaturalLanguage: 'Ask questions in natural language',
    beSpecific: 'Be specific about your legal area',
    askClarification: 'Ask for clarification if needed',
    checkSources: 'Check sources for verification',
    divorceProcess: 'Divorce Process',
    theftPenalties: 'Theft Penalties',
    employeeRights: 'Employee Rights',
    marriageRequirements: 'Marriage Requirements',
    childCustody: 'Child Custody'
  },
  am: {
    home: 'ሆም',
    laws: 'ሕጎች',
    assistant: 'አይ ረዳት',
    about: 'ስለ እኛ',
    login: 'ግባ',
    register: 'ተመዝገብ',
    logout: 'ውጣ',
    dashboard: 'ዳሽቦርድ',
    profile: 'መገለጫ',
    bookmarks: 'ዕልባቶች',
    search: 'ፈልግ',
    searchPlaceholder: 'ሕጎችን፣ አንቀጾችን ይፈልጉ ወይም ጥያቄ ይጠይቁ...',
    searchResults: 'የፍለጋ ውጤቶች',
    noResults: 'ምንም ውጤት አልተገኘም',
    criminalLaw: 'የወንጀል ሕግ',
    familyLaw: 'የቤተሰብ ሕግ',
    laborLaw: 'የሠራተኛ ሕግ',
    constitution: 'ሕገ መንግሥት',
    loading: 'በመጫን ላይ...',
    error: 'ስህተት',
    success: 'ስኬት',
    save: 'አስቀምጥ',
    cancel: 'ሰርዝ',
    delete: 'ሰርዝ',
    edit: 'አርትዕ',
    view: 'ተመልከት',
    back: 'ተመለስ',
    next: 'ቀጣይ',
    previous: 'ቀዳሚ',
    footerDescription: 'የኢትዮጵያ የሕግ መመሪያ ሥርዓት - ፍትህን ለሁሉም በቴክኖሎጂ ተደራሽ ማድረግ።',
    copyright: 'የኢትዮጵያ የሕግ መመሪያ ሥርዓት። መብቱ በሕግ የተጠበቀ ነው።',
    privacy: 'የግላዊነት ፖሊሲ',
    terms: 'የአገልግሎት ውል',
    contact: 'አግኙን',
    aiAssistant: 'የሕግ አይ ረዳት',
    aiAssistantDescription: 'ስለ ኢትዮጵያ የወንጀል፣ የቤተሰብ እና የሠራተኛ ሕግ ይጠይቁኝ',
    online: 'በመስመር ላይ - 24/7',
    send: 'ላክ',
    aiDisclaimer: 'ይህ አይ አጠቃላይ የሕግ መረጃ ብቻ ይሰጣል። ለተወሰነ የሕግ ምክር ብቃት ያለው ጠበቃ ያማክሩ።',
    suggestedQuestions: 'የተጠቆሙ ጥያቄዎች:',
    chatPlaceholder: 'የሕግ ጥያቄዎን እዚህ ይተይቡ...',
    all: 'ሁሉም',
    keyword: 'ቁልፍ ቃል',
    naturalLanguage: 'ተፈጥሯዊ ቋንቋ',
    searching: 'የሕግ ዳታቤዝ በመፈለግ ላይ...',
    tryDifferentKeywords: 'የተለያዩ ቁልፍ ቃላት ይሞክሩ ወይም ከዚህ በታች ያሉትን የሕግ ምድቦች ይመልከቱ',
    results: 'ውጤቶች',
    foundIn: 'ተገኝቷል በ',
    sortByRelevance: 'ደርድር በ: ተዛማጅነት',
    sortByDate: 'ደርድር በ: ቀን',
    sortByTitle: 'ደርድር በ: ርዕስ',
    views: 'ትይታዎች',
    share: 'አጋራ',
    readMore: 'ተጨማሪ ያንብቡ',
    clearAll: 'ሁሉንም አጽዳ',
    allCategories: 'ሁሉም ምድቦች',
    allLanguages: 'ሁሉም ቋንቋዎች',
    allTime: 'ሁልጊዜ',
    today: 'ዛሬ',
    thisWeek: 'በዚህ ሳምንት',
    thisMonth: 'በዚህ ወር',
    thisYear: 'በዚህ ዓመት',
    clearHistory: 'ታሪክ አጽዳ',
    useKeywords: 'ቁልፍ ቃላት ተጠቀም',
    keywordsTip: 'እንደ "ፍቺ"፣ "ስርቆት"፣ ወይም "ዝቅተኛ ደመወዝ" ያሉ የተወሰኑ ቃላትን ይሞክሩ',
    naturalLanguageTip: 'እንደ "ለፍቺ ምክንያቶች ምንድን ናቸው?" ያሉ ጥያቄዎችን ይጠይቁ',
    browseCategories: 'ምድቦችን ይመልከቱ',
    browseTip: 'ወይም ምን መፈለግ እንዳለቦት እርግጠኛ ካልሆኑ ሕጎችን በምድብ ይመልከቱ',
    loadingCategory: 'ምድብ በመጫን ላይ...',
    categoryNotFound: 'ምድብ አልተገኘም',
    backToCategories: 'ወደ ምድቦች ተመለስ',
    articles: 'አንቀጾች',
    showing: 'እያሳየ ነው',
    of: 'ከ',
    last30Days: 'ያለፉት 30 ቀናት',
    mostPopular: 'በጣም ታዋቂ',
    saves: 'ቁጠባዎች',
    quickSearch: 'ፈጣን ፍለጋ...',
    viewAll: 'ሁሉንም ተመልከት',
    newSearch: 'አዲስ ፍለጋ',
    startChat: 'ውይይት ጀምር',
    savedArticles: 'የተቀመጡ አንቀጾች',
    recentActivity: 'የቅርብ ጊዜ እንቅስቃሴዎች',
    recommended: 'ለእርስዎ የሚመከር',
    quickAccess: 'ፈጣን መዳረሻ',
    continueLearning: 'መማርዎን ይቀጥሉ',
    continue: 'ቀጥል',
    searchedFor: 'ፈልገዋል',
    saved: 'አስቀምጠዋል',
    askedAbout: 'ጠይቀዋል ስለ',
    basedOnSearches: 'በቅርብ ፍለጋዎችዎ መሠረት',
    popularInProfession: 'በሙያዎ ዘንድ ታዋቂ',
    frequentlyViewed: 'በተደጋጋሚ የታየ',
    loadingDashboard: 'ዳሽቦርድዎን በመጫን ላይ...',
    viewAllActivity: 'ሁሉንም እንቅስቃሴዎች ተመልከት',
    allBookmarks: 'ሁሉም ዕልባቶች',
    items: 'ንጥሎች',
    export: 'ላክ',
    mostViewed: 'በጣም የታየ',
    lastAdded: 'መጨረሻ የተጨመረ',
    total: 'ጠቅላላ',
    categories: 'ምድቦች',
    criminalCode: 'የወንጀል ሕግ',
    viewed: 'ታይቷል',
    hoursAgo: 'ሰዓታት በፊት',
    loadingBookmarks: 'ዕልባቶችዎን በመጫን ላይ...',
    loginToViewBookmarks: 'እባክዎ ዕልባቶችዎን ለማየት ይግቡ',
    goToLogin: 'ወደ መግቢያ ይሂዱ',
    noBookmarks: 'ገና ዕልባቶች የሉም',
    startSavingContent: 'በፍጥነት ለመድረስ የሕግ ይዘቶችን ማስቀመጥ ይጀምሩ',
    browseLaws: 'ሕጎችን ይመልከቱ',
    selectAll: 'ሁሉንም ምረጥ',
    remove: 'አስወግድ',
    personalInfo: 'የግል መረጃ',
    fullName: 'ሙሉ ስም',
    email: 'ኢሜይል አድራሻ',
    phone: 'ስልክ ቁጥር',
    profession: 'ሙያ',
    selectProfession: 'ሙያ ይምረጡ',
    student: 'ተማሪ',
    lawyer: 'ጠበቃ',
    judge: 'ዳኛ',
    legalResearcher: 'የሕግ ተመራማሪ',
    businessOwner: 'የንግድ ባለቤት',
    other: 'ሌላ',
    bio: 'ስለ ራስዎ',
    bioPlaceholder: 'ስለ ራስዎ ትንሽ ይንገሩን...',
    saveChanges: 'ለውጦችን አስቀምጥ',
    changePassword: 'የይለፍ ቃል ይቀይሩ',
    currentPassword: 'የአሁኑ የይለፍ ቃል',
    newPassword: 'አዲስ የይለፍ ቃል',
    confirmPassword: 'አዲስ የይለፍ ቃል ያረጋግጡ',
    passwordRequirements: 'የይለፍ ቃል መስፈርቶች:',
    minLength: 'ቢያንስ 6 ቁምፊዎች ረጅም',
    uppercaseRequired: 'ቢያንስ አንድ አቢይ ሆሄ',
    numberRequired: 'ቢያንስ አንድ ቁጥር',
    updatePassword: 'የይለፍ ቃል አዘምን',
    preferences: 'ምርጫዎች',
    displaySettings: 'ማሳያ ቅንብሮች',
    language: 'ቋንቋ',
    fontSize: 'የፊደል መጠን',
    small: 'ትንሽ',
    medium: 'መካከለኛ',
    large: 'ትልቅ',
    darkMode: 'ጨለማ ሁነታ',
    notifications: 'ማሳወቂያዎች',
    emailNotifications: 'የኢሜይል ማሳወቂያዎች',
    savePreferences: 'ምርጫዎችን አስቀምጥ',
    accountStatus: 'የመለያ ሁኔታ',
    verified: 'የተረጋገጠ',
    notVerified: 'አልተረጋገጠም',
    disabled: 'አይሰራም',
    memberSince: 'አባል የሆነበት',
    manageAccount: 'መለያ ያስተዳድሩ',
    securityTips: 'የደህንነት ምክሮች',
    useStrongPassword: 'ጠንካራ የይለፍ ቃል ይጠቀሙ',
    enable2FA: '2-ደረጃ ማረጋገጫ ያንቁ',
    dontShareCredentials: 'የመለያ መረጃዎን አያጋሩ',
    logoutFromSharedDevices: 'ከተጋሩ መሣሪያዎች ይውጡ',
    connectedAccounts: 'የተገናኙ መለያዎች',
    connected: 'ተገናኝቷል',
    connect: 'ተገናኝ',
    loadingProfile: 'መገለጫ በመጫን ላይ...',
    loggedInFromNewDevice: 'ከአዲስ መሣሪያ ገብተዋል',
    chatWithAI: 'ከአይ ረዳት ጋር ውይይት',
    loginToViewProfile: 'እባክዎ መገለጫዎን ለማየት ይግቡ',
    searches: 'ፍለጋዎች',
    chatSessions: 'የውይይት ክፍለ ጊዜዎች',
    bookmarks: 'ዕልባቶች',
    security: 'ደህንነት'
  },
  om: {
    home: 'Mana',
    laws: 'Seera',
    assistant: 'Gargaarsa AI',
    about: 'Waa\'ee',
    login: 'Seeni',
    register: 'Galmaa\'i',
    logout: 'Ba\'i',
    dashboard: 'Dawashboordii',
    profile: 'Proofaayilii',
    bookmarks: 'Qabiyyee',
    search: 'Barbaadi',
    searchPlaceholder: 'Seera, artikili barbaadi ykn gaaffii gaafadhu...',
    searchResults: 'Bu\'aalee Barbaacha',
    noResults: 'Bu\'aan hin argamne',
    criminalLaw: 'Seera Cubbuu',
    familyLaw: 'Seera Maatii',
    laborLaw: 'Seera Hojii',
    constitution: 'Heera Mootummaa',
    loading: 'Fe\'aa jira...',
    error: 'Dogoggora',
    success: 'Milkaa\'ina',
    save: 'Kaayyoo',
    cancel: 'Haqi',
    delete: 'Haqi',
    edit: 'Barreeffama',
    view: 'Ilaali',
    back: 'Duuba',
    next: 'Kan itti aanu',
    previous: 'Kan duraa',
    footerDescription: 'Sirna Qajeelfama Seera Etiyophiaa - Teeknooloojiidhaan haqa nama hundaaf dhaqqabsiisuu.',
    copyright: 'Sirna Qajeelfama Seera Etiyophiaa. Mirgi hundi eegama.',
    privacy: 'Imaammata Dhuunfaa',
    terms: 'Walii galtee Tajaajila',
    contact: 'Nu Qunnami',
    aiAssistant: 'Gargaarsa Seeraa AI',
    aiAssistantDescription: 'Waa\'ee Seera Cubbuu, Maatii fi Hojii Etiyophiaa na gaafadhu',
    online: 'Online - 24/7',
    send: 'Ergi',
    aiDisclaimer: 'AI kun oduu seeraa waliigalaa qofa kenna. Gorsa seeraa addaaf, maaloo abukaattoo ga\'aa gorsadhu.',
    suggestedQuestions: 'Gaaffilee eeggaman:',
    chatPlaceholder: 'Gaaffii seeraa kee as barreessi...',
    all: 'Hunda',
    keyword: 'Jecha cimdii',
    naturalLanguage: 'Afaan uumamaa',
    searching: 'Kuusaa seeraa barbaadaa jira...',
    tryDifferentKeywords: 'Jechoota cimdii garaa garaa yaali ykn ramaddii seeraa asii gadii ilaali',
    results: 'Bu\'aalee',
    foundIn: 'argame',
    sortByRelevance: 'Adeemsi: Madaalaan',
    sortByDate: 'Adeemsi: Guyyaan',
    sortByTitle: 'Adeemsi: Matadureen',
    views: 'ilaalcha',
    share: 'Hir\'isi',
    readMore: 'Dabalata Dubbisi',
    clearAll: 'Hunda haqi',
    allCategories: 'Ramaddii Hunda',
    allLanguages: 'Afaanota Hunda',
    allTime: 'Yeroo Hunda',
    today: 'Har\'a',
    thisWeek: 'Torban kana',
    thisMonth: 'Ji\'a kana',
    thisYear: 'Bara kana',
    clearHistory: 'Seenaa haqi',
    useKeywords: 'Jechoota cimdii fayyadami',
    keywordsTip: 'Jechoota addaa akka "hiikkaa", "hattoomaa", ykn "mindaa xiqqaa" yaali',
    naturalLanguageTip: 'Gaaffilee akka "Sababni hiikkaa maal fa\'a?" gaafadhu',
    browseCategories: 'Ramaddii ilaali',
    browseTip: 'Ykn waan barbaaddu hin beekne ta\'e, seera ramaddiidhaan ilaali',
    loadingCategory: 'Ramaddii fe\'aa jira...',
    categoryNotFound: 'Ramaddiin hin argamne',
    backToCategories: 'Gara ramaddii duuba',
    articles: 'artikiloota',
    showing: 'Agarsiisaa jira',
    of: 'keessaa',
    last30Days: 'Guyyoota 30 darban',
    mostPopular: 'Baay\'ee beekamaan',
    saves: 'Kaayyoo',
    quickSearch: 'Barbaacha salphaa...',
    viewAll: 'Hunda Ilaali',
    newSearch: 'Barbaacha Haaraa',
    startChat: 'Haasa\'a jalqabi',
    savedArticles: 'Artikiloota Kaayyamte',
    recentActivity: 'Sochii Dhihoo',
    recommended: 'Siif Gorfamu',
    quickAccess: 'Dhaqqabannaa Salphaa',
    continueLearning: 'Barumsa Itti Fufi',
    continue: 'Itti fufi',
    searchedFor: 'Barbaaddeef',
    saved: 'Kaayyateef',
    askedAbout: 'Gaafateef waa\'ee',
    basedOnSearches: 'Barbaacha dhihoo kee irratti hundaa\'a',
    popularInProfession: 'Ogummaa kee keessatti beekamaa dha',
    frequentlyViewed: 'Yeroo baay\'ee ilaalame',
    loadingDashboard: 'Dawashboordii kee fe\'aa jira...',
    viewAllActivity: 'Sochii Hunda Ilaali',
    allBookmarks: 'Qabiyyee Hunda',
    items: 'Wantoota',
    export: 'Ergi',
    mostViewed: 'Baay\'een ilaalame',
    lastAdded: 'Dhumaa kan dabale',
    total: 'Waliigala',
    categories: 'Ramaddii',
    criminalCode: 'Seera Cubbuu',
    viewed: 'Ilaalame',
    hoursAgo: 'sa\'aatii dura',
    loadingBookmarks: 'Qabiyyee kee fe\'aa jira...',
    loginToViewBookmarks: 'Maaloo qabiyyee kee ilaaluuf seeni',
    goToLogin: 'Gara Seensa Dhaqi',
    noBookmarks: 'Qabiyyee hin jiru',
    startSavingContent: 'Qabiyyee seeraa kaayyachuu jalqabi ariitiidhaan argachuuf',
    browseLaws: 'Seera Ilaali',
    selectAll: 'Hunda Filadhu',
    remove: 'Haqi',
    personalInfo: 'Oduu Dhuunfaa',
    fullName: 'Maqaa Guutuu',
    email: 'Teessoo Imeelii',
    phone: 'Lakkoofsa Bilbilaa',
    profession: 'Ogummaa',
    selectProfession: 'Ogummaa filadhu',
    student: 'Barataa',
    lawyer: 'Abukaattoo',
    judge: 'Abbaa seera',
    legalResearcher: 'Qorataa Seeraa',
    businessOwner: 'Abbaa Daldalaa',
    other: 'Kan biraa',
    bio: 'Waa\'ee kee',
    bioPlaceholder: 'Waa\'ee kee xinnoo nuuf himi...',
    saveChanges: 'Jijjiirama Kaayyadhu',
    changePassword: 'Jecha Icciitii Jijjiiri',
    currentPassword: 'Jecha Icciitii Ammaa',
    newPassword: 'Jecha Icciitii Haaraa',
    confirmPassword: 'Jecha Icciitii Haaraa Mirkaneessi',
    passwordRequirements: 'Barbaachisoowwan Jecha Icciitii:',
    minLength: 'Xiqqaatti 7 arfiilee dheeraa',
    uppercaseRequired: 'Xiqqaatti qubee guddaa tokko',
    numberRequired: 'Xiqqaatti lakkoofsa tokko',
    updatePassword: 'Jecha Icciitii Haaromsi',
    preferences: 'Filannoo',
    displaySettings: 'Sirreeffama Agarsiisa',
    language: 'Afaan',
    fontSize: 'Guddina Barreeffamaa',
    small: 'Xiqqaa',
    medium: 'Giddu galeessa',
    large: 'Guddaa',
    darkMode: 'Haala Dukkanaa\'aa',
    notifications: 'Beeksisawwan',
    emailNotifications: 'Beeksisawwan Imeelii',
    savePreferences: 'Filannoo Kaayyadhu',
    accountStatus: 'Haala Herregaa',
    verified: 'Mirkanaa\'e',
    notVerified: 'Hin mirkanaa\'in',
    disabled: 'Hin hojjnu',
    memberSince: 'Miseensa ture',
    manageAccount: 'Herrega Mee',
    securityTips: 'Qarqarsa Nagaa',
    useStrongPassword: 'Jecha icciitii cimaa fayyadami',
    enable2FA: 'Mirkaneessa 2-dhaan qindeessi',
    dontShareCredentials: 'Oduu herregaa kee hin hir\'isin',
    logoutFromSharedDevices: 'Meessisa qoodame irraa ba\'i',
    connectedAccounts: 'Herregoota Hidhaman',
    connected: 'Hidhame',
    connect: 'Hidhadhu',
    loadingProfile: 'Proofaayilii fe\'aa jira...',
    loggedInFromNewDevice: 'Meessisa haaraa irraa seente',
    chatWithAI: 'Gargaarsa AI wajjin haasa\'i',
    loginToViewProfile: 'Maaloo proofaayilii kee ilaaluuf seeni',
    searches: 'Barbaacha',
    chatSessions: 'Haasa\'a',
    bookmarks: 'Qabiyyee',
    security: 'Nagaa'
  }
}

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    const saved = localStorage.getItem('language')
    return saved || 'en'
  })

  useEffect(() => {
    localStorage.setItem('language', currentLanguage)
    document.documentElement.lang = currentLanguage
  }, [currentLanguage])

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setCurrentLanguage(lang)
    }
  }

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key
  }

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    translations: translations[currentLanguage],
    availableLanguages: [
      { code: 'en', name: 'English', flag: '🇬🇧' },
      { code: 'am', name: 'አማርኛ', flag: '🇪🇹' },
      { code: 'om', name: 'Afaan Oromoo', flag: '🇪🇹' }
    ]
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}